---
- hosts: ocean
  roles:
    - role: geerlingguy.git
    - role: staticsite
    - role: jdauphant.nginx
      become: yes
      nginx_http_params:
        - sendfile "on"
        - access_log /var/log/nginx.log
      nginx_sites:
        static:
          - listen 80
          - root /srv/www/sckoonet
          - location / { try_files $uri $uri/ /index.html; }
      nginx_configs:
        proxy:
          - proxy_set_header X-Real-IP  $remote_addr
          - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
